caldav/objects.py
This PR fixes #14. The fix was quite simple but seems to do the trick.
=> Bugfix: Calendar.todos() now returns todos without a status

example/icloud_example.py
Added example directory with code for connecting to iCloud. COntains a class to wrap around caldav which  provides discovery service to retrieve principal and calendar-home-set urls for iCloud accounts.
=> Add iCloud example code

MANIFEST.in
The changelog can be useful for people trying to find out what changed and tests can be executed by the vendors to validate their python stack if it works with the caldav release.
=> Include tests and changelog in pypi sdist tarball

caldav/objects.py
Fix use of datetime.now.
The top of objects.py has:
from datetime import datetime
so further on in the file, code should use datetime.now() rather than
datetime.datetime.now().
=> Fix use of datetime.now.

caldav/elements/cdav.py, setup.py, tests/test_cdav.py
Apparently pull request #59 killed python 2.7-compatibility.  This is an attempt on mending it.
=> Attempt on reintroducing support for python 2.7

MANIFEST.in, README.md, setup.py
The goal of this PR is to provide a description at https://pypi.org/project/caldav/ in order to replace the current text:
```
The author of this package has not provided a project description
```
I don't know which command is used to create the package but, according to `python setup.py sdist bdist_wheel`, it should work.
=> Add long description to the package

Makefile, setup.cfg
This PR is a draft for issue https://github.com/python-caldav/caldav/issues/77
The Makefile allows to:
- run the tests with `tox`,
- build the package,
- build the documentation,
- clean the directory.
It supposes that `tox` is installed on the system. I can modify it to install `tox` package in a `virtualenv` if you prefer.
I'm unsure about the real command runned to build the package but it works.
I can add a command for `nosetest` too.
=> run tox and add targets in Makefile

caldav/objects.py
When full url is included in the response shown like below, some errors are apperred.
```xml
<d:multistatus xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
<d:response>
<d:href>http://cal.example.com/home/bernard/</d:href>
<d:propstat>
<d:prop>
<c:calendar-home-set>
<d:href>http://cal.example.com/home/bernard/calendars/</d:href>
</c:calendar-home-set>
</d:prop>
<d:status>HTTP/1.1 200 OK</d:status>
</d:propstat>
</d:response>
</d:multistatus>
```
_from an example shown in https://tools.ietf.org/html/rfc4791#section-6.2.1_
I fixed them with:
- avoid `quote` from a target of `url.join` if it's full url because 'https://\~' will be encoded to 'https%3A//\~' occurred with a change of https://github.com/python-caldav/caldav/commit/8f0c0e5d7e4cdf88b5c2e4260f114b405d8e4085
- use full url …
=> Fix errors with full url response

caldav/davclient.py
=> Enable HTTP keepalive and pooling by using requests.Session()

tests/test_caldav.py
Fix mocked method - davclient is now using requests.Session.request rather than requests.request.
=> Fix mocked method - davclient is now using requests

caldav/elements/cdav.py, caldav/objects.py
This server returns empty data result (URL only) from date search.
So we have to re-query the data for every event after fetching urls. calendar_multiget() has been added for it.
And the exception on _calendar_comp_class_by_data() on empty data result has been fixed
=> Fixed a problem on certain caldav server (LINE Works).

caldav/davclient.py
This adds the keyword argument ```ssl_cert```to the ```__init__```method of ```DAVClient```. The idea is to allow for passing a client certificate to the requests module. 
Maybe, you might want to integrate this.
=> Add ssl_cert to DAVClient for client certificate support

caldav/davclient.py
Some servers, like really old SabreDAV based servers, seem to choke on password if we pass a bytes sequence instead of a string to the "requests" libraries HTTPDigestAuth object.
This fix against master retries authentication in case of authentication failure with the same password as plain string.
Related: #167 (same fix, but for v0.8-stable)
Fixes #165 
Fixes #164
=> Fix digest auth with pre utf8 servers (version for master)

caldav/davclient.py
This PR adds support for PEP 343 
It makes sense to be able to use with-statements with the DAVClient object, as some might want to close the DAVClient regardless of whether there were any errors. One would have to use a try-finally statement, but PEP 343 recommends using a with-statement
Currently the user has to invoke `DAVClient.session.close()` to fully close the `requests.Session` object. This PR adds support for the following Syntax:
```python3
with DAVClient(url) as dav:
...
```
If any error occurs during the with block, the requests session will still be closed regardless
Another improvement should be a publicly available `DAVClient.close()` function which closes the `requests.Session()` adapter, otherwise one has to use `DAVClient.session.close()`
Kind regards
neonfighter28
=> add ctx manager support for davclient (PEP 343)

caldav/davclient.py
I am using mailcow behind a reverse proxy and mailcow returns the auth_type "basic" in lower case.
Therefore I propose that the match should be case insensitive
=> Ignore case of `auth_type`

caldav/davclient.py
I am unable to connect to my Baikal server as the `WWW-Authenticate` header returns title case `Digest` while the code checks for lowercase `digest`.
Hoping this plus the fixes in https://github.com/python-caldav/caldav/pull/176 will fix the issue described here: https://github.com/home-assistant/core/issues/65804
=> auth_type to lower case for SabreDAV type servers

.gitignore, docs/source/index.rst, setup.cfg
This patch fixes the tox unit test command, and adds tests for python 3.9 and python 3.10
=> Tox newer environments

caldav/lib/vcal.py, setup.cfg, setup.py, tests/test_caldav.py, tests/test_caldav_unit.py
This patch:
- installs pytest and pytest-cov to run the tests
- configure tox so it runs with pytest
- replace nose style assertions `assert_equal`, `assert_not_equal` and `assert_raises` with their pytest equivalents `assert` and `with pytest.raises`
- fixes a couple of warnings raised by pytest about regex string missing `r` flag
Before nose can be totally removed, it is needed to replace the `SkipTest` exception with the pytest `@pytest.mark.skip` or `@pytest.mark.skipif` decorator equivalent.
https://github.com/python-caldav/caldav/blob/6b791de7ccae48901ada8318158ae824f8f36982/tests/test_caldav.py#L25
Though it is not as simple as I expected so I havn't implement this in this patch.
Fixes partially #196
=> use pytest instead of nosetests

.github/workflows/tests.yaml, docs/source/conf.py, setup.cfg
This patch adds a tox environment that builds the documentation. It is plugged to GHA so documentation build is tested at every commit.
=> Build documentation with tox

caldav/davclient.py
I run `caldav` requests every 15 minutes in an endless loop and eventually my program will freeze indefinitely. This is because by default the `requests` library uses a `timeout` value of `None` which equates to an infinite timeout value. This PR allows developers to instantiate `DAVClient` with an optional `timeout` value that is passed on to the `request` method call.
=> Allow requests connection timeout to be set

caldav/lib/url.py, tests/test_caldav_unit.py
The pickle module calls `getattr`[1] when unpickling a URL.  Make it so
that `__getattr__` doesn't assume that `self.url_parsed` exists so that
unpickle will work.
[1] https://docs.python.org/3/library/pickle.html#pickle-inst
=> make URL picklable

caldav/objects.py
Requested get_name convenience method created for Calendar object.
Returns name object attribute.
Docstring indicates that a None object is returned if a name is not set - maybe this is beyond the scope of this method's knowledge though?
=> Added get_name convenience method for Calendar

caldav/lib/error.py, caldav/lib/python_utilities.py, caldav/lib/vcal.py, caldav/objects.py, examples/basic_usage_examples.py, setup.py, tests/compatibility_issues.py, tests/test_caldav.py, tests/test_caldav_unit.py
Most objects returned from the caldav server has one vcalendar with one subcomponent, which may be an Event, Todo, Journal or FreeBusy from the icalendar library. However, some calendar servers may also return a Timezone subcomponent. (and in addition, when there are recurrences involved, an object may have multiple recurrences given as subcomponents).
It seems like I've encountered this before and created an object._icalendar_object which looks through the subcomponents and return the first relevant subcomponent found - but then forgotten about this method, and creating code just asserting that the data we're looking for is available as self.icalendar_instance.subcomponents[0].
With this pull request, I'm removing the first underscore from the said method to indicate that it's a public …
=> various fixes, improved reliability

setup.py, tests/test_caldav.py
Nose was only used to raise SkipTest that can be done with pytest.skip and that old dependency can be removed.
=> Remove nose dependency

caldav/objects.py
This should fix https://github.com/python-caldav/caldav/issues/241 properly
=> recurring_ical_event 2.0 does not expand tasks by default

caldav/objects.py
Some new features needed for my `plann`-tool at https://github.com/tobixen/plann:
* search method now supports things like `no_category` etc to find calendar components missing such properties (but there is no ftesting on this ... will raise a separate issue on that)
* `get_duration` is now supported both for events and tasks - (but it should be moved to the icalendar library eventually - pending https://github.com/collective/icalendar/issues/496)
=> New features for calendar_cli aka plann

caldav/__init__.py, caldav/lib/error.py, caldav/lib/vcal.py, caldav/objects.py, docs/source/conf.py, docs/source/index.rst, setup.py, tests/test_caldav.py
Some unrelated, minor commits:
* Bugfix, the parent/child code didn't work - now with test code.
* The version number has been moved from setup.py to __init__.py
* Documentation wrg backward-compatibility support and legacy python support
* Now we are incompatible with recurring_ical_event 1.x, mark this in setup.py
=> Bugfixes, docfix and making __version__ available

caldav/lib/vcal.py, caldav/objects.py, tests/test_caldav_unit.py, tests/test_vcal.py
* Zimbra may apparently create events with both DTSTART, DTEND and DURATION, which is a breach of the standard.  A simple workaround has been implemented, just throwing away redundant information.  No check done on weather the DURATION matches DTEND-DTSTART (it did in the ical data I got from Zimbra), so this one may potentially throw away information.  (I just wrote a message to the organizer asking if the original ical data was actually produced internally Zimbra or by some other client).
* I've been fighting a bit with some proprietary system in #201 that have some partial and slightly non-compliant support for caldav - and made some partial workaround for loading content from it.
* One extra unrelated commit enhancing the tests code has been piggy-backed on this pull request.
=> Workarounds for broken caldav servers

caldav/lib/vcal.py, caldav/objects.py, tests/conf.py, tests/test_vcal.py
Various minor fixes needed for the rewritten basic_usage_examples.py to work properly:
* Two bugfixes (and one extra line in the tests catching one of them) wrg of the possibility to create events or tasks based on some `ical_fragment`.  This seems not to have sufficient test code.  Hm.
* I think that `len(calendar.objects)` ought to work.  Apparently it didn't.
=> Bugfixings

caldav/__init__.py, caldav/objects.py, docs/source/index.rst, examples/basic_usage_examples.py, tests/test_caldav.py
This is a collection of things that does not alter the caldav code itself:
* Version number pushed from 0.x to 1.0.  References #92,
* Comments in the code, docstrings, and minor changes to a deprecation warning.  Particularly TODO-comments and deprecation-comments.
* Deprecation-policy nailed in the doc.  Things that are marked as DEPRECATED by now *may* be removed in version 2.0.  Version 1.x will (most likely) be supported at least for 3 years, probably more.
* basic_usage_examples.py has been totally rewritten (and tested).
* Minor change in the test framework - checking for the `caldav_servers[i]["enable"]` attribute has been moved from test_caldav.py to conf.py (was needed for being able to test the basic_usage_examples.py.
(note: some minor bugfixes and enhancements were needed to …
=> Meta - documentation, comments, example code

caldav/lib/vcal.py
Let's convert it to UTC before sending it to the server, if no timezone is given.
=> we shouldn't push timezone-naive timestamps to the calendar server

caldav/objects.py
Potential fix for issue #267 - though not very well tested
=> Potential fix for issue #267

caldav/__init__.py, caldav/lib/vcal.py, caldav/objects.py
* If a component was given with full ical (including the BEGIN:VCALENDAR-tag) but (a) leading blank(s), and some other field also was given, then the BEGIN/END:VCALENDAR tags got duplicated
* is-defined and is-not-defined search for class did not work
* New icalendar generation code: don't autogenerate a uuid if we already have an uuid
* Some exception got thrown in the get_duration-logic.
=> misc bugfixes

examples/basic_usage_examples.py
=> Tweaking the examples

caldav/objects.py
I think I considered that an URL or path could be passed via the `cal_id`-parameter, but ... it doesn't work.
=> Allow principle.calendar(calendar_url=...)

caldav/lib/vcal.py
* STATUS should by default be set to NEEDS-ACTION.  Note that this only applies when no icalendar data is given.  NEEDS-ACTION is the implied default.  DAViCal needs it explicitly set, ref https://gitlab.com/davical-project/davical/-/issues/281
=> DAViCal workarounds

caldav/objects.py
By default, the code would break with an ugly assert if doing `obj.icalendar_component` and the obj contained a recurrance set.  I think that in almost all cases it will be harmless to yield the first component in the recurrence set, and I'm pretty sure that assert will blow up things for people, so I change the default to not assert anything.
(maybe we should yield a rate-limited error message instead?)
=> Remove annoying assert from icalendar_component

caldav/objects.py, tests/test_caldav.py
The flag check_dependent will check the RELATED-TO attribute and if there is some dependent ticket with a lower DUE, an error will be raised.
This feature was made for plann.
=> Allow checking DUE on dependent before moving DUE

caldav/objects.py
* `obj.load(only_if_unloaded=True)` will be a noop if there exists data
* new method `obj.is_loaded()`
* earlier workaround modified to use the new method
=> allow conditional load

caldav/objects.py, tests/test_caldav.py
`__str__` will always return name (and may cause server traffic) while `__repr__` will show the URL (and will not cause server traffic - but will basically show everything needed to recreate the calendar object).
Earlier `__str__` would show name if it was available, otherwise URL, and would never initiate server traffic - and `__repr__` was calling `__str__`.
=> cal_obj.__str__ and cal_obj.__repr__ should be deterministic

caldav/objects.py
The test covering the synchronization code suddenly broke towards one of the servers; the URLs kept by the objects was non-deterministic, sometimes containing `:443` and sometimes not.  Now we're running `obj.url = obj.url.canonical()` to force through deterministic URLs and allow the tests to pass.
=> keep canonical URLs in synchronization objects

caldav/objects.py, tests/test_caldav_unit.py
Some test broke towards some server because the server threw empty icalendar objects back at us - objects containing `BEGIN:VCALENDAR` and `END:VCALENDAR` and a little bit of metadata, but no components.  This was working out earlier while the `vobjects` library was used to determinate if client-side expansion was needed or not, but when changing to `obj.icalendar_component` we got an assertion error back.  Now the code is changed so that search items that have no data *or* no components to them will be loaded.   This may cause very much longer loading times, but the decision was sort of made in 1.0.1 already - this will happen only on a few calendar servers that are breaching the RFC.
Also cleaned a bit up/refactored, to always use the new `.load(only_if_unloaded=True)` rather than …
=> compatibility fix: objects returned by search should always be loaded

caldav/objects.py, tests/test_caldav.py, tests/test_caldav_unit.py
* the new cleanup logic didn't work out very well on calendars where it's needed with unique calendar IDs
* the new testSetDue-test created a calendar which would only work for events, and then tried using it for tasks
=> various fixes to the test code

changelog-1.1.md, tests/compatibility_issues.py
added some more entries to the list of servers that does not support search queries containing is-not-defined
=> Polishing before release

caldav/davclient.py, caldav/elements/base.py, caldav/lib/python_utilities.py, caldav/lib/url.py, changelog-1.1.md, setup.py, tests/compatibility_issues.py, tests/proxy.py, tests/test_caldav.py, tests/test_caldav_unit.py
Python 2 went EOL on 1/1/2020 and we receive no more support from the Python Core Team after Python 2.7.18 even for known security issues.
This removes the six package from dependencies.
=> Drop python2 support

caldav/davclient.py
Fix logger, error message was :
```
File "/home/arnaud/.local/lib/python3.10/site-packages/caldav/davclient.py", line 77, in __init__
"Expected some valid XML from the server, but got this: \n"
TypeError: can only concatenate str (not "bytes") to str
```
=> fix log message : argument was bytes not String

caldav/objects.py
Related issue: #310 
This PR avoid a crash when the VCALENDAR does not contains a VEVENT component.
=> Avoid crashing when object's component is missing

caldav/objects.py
To address #313: lack of ID field populating in "all calendar" request.  I included fall-back in case the URL isn't as I expect.
=> Unpack id when populating all calendar list

docs/source/index.rst
Just fixed three typos I noticed while reading the documentation.
=> Fix typos in documentation

caldav/davclient.py
`DAVResponse` already has class-level `davclient = None` set, looks like it is not set on instance-level by accident.
=> Don't forget to set `.davclient` in `DAVResponse`

caldav/objects.py
Method failed before when using a custom relation type. Specification explicitly allows custom X-Types for non-standardized use cases. This also makes the library future-proof if futher relation types are added.
Also extract RELTYPE_REVERSER constant from method for good practice.
Tested for my use case (using a custom type) locally.
=> set_related: allow custom types with set_reversed=False

caldav/objects.py
- workarounds https://github.com/collective/icalendar/issues/557
- fixes #334 
- see issue description for reasoning
=> work around icalendar ignoring additional parameters

caldav/objects.py
We faced the problem that icalendar_component missing in some cases. Added checks if the event has the icalendar_component attribute.
=> Fix missing icalendar_component

caldav/lib/vcal.py
The lack of initialization of the `stamped` variable was causing a failure from an unexpected place when running it with a faulty ical that lacked a `BEGIN:V…` before having the first `DTSTAMP`. Probably the same with `ended`. Only affects bad strings, so it’s more of an error handling improvement…
=> Initialize stamped and ended, implementing the small optimization todo

tests/test_vcal.py
The pull request #347 didn’t contain a test that showed the difference, so here it is. Without the fix, the test would’ve failed like:
```python
…
for ical in non_broken_ical:                                            
>               assert vcal.fix(ical) == ical
tests/test_vcal.py:262:                                                             
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
caldav/lib/vcal.py:81: in fix             
"\n".join(filter(LineFilterDiscardingDuplicates(), fixed.strip().split("\n")))  
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <caldav.lib.vcal.LineFilterDiscardingDuplicates object at 0x7a99fd022820>    
line = 'DTSTAMP:20210205T101751Z' …
```
=> Add example in test for stamped initialization issue from #347

CHANGELOG.md, caldav/__init__.py, caldav/davclient.py, caldav/elements/base.py, caldav/elements/cdav.py, caldav/elements/dav.py, caldav/elements/ical.py, caldav/lib/debug.py, caldav/lib/error.py, caldav/lib/namespace.py, caldav/lib/url.py, caldav/lib/vcal.py, caldav/objects.py, caldav/requests.py, setup.py, tests/test_caldav.py
This fixes #328 by inlining type hints from typeshed caldav. Types were later fixed and further implemented where missing.
Tests all pass using Xandikos. davical was also tested, here 3 tests fail which also fail with the current master:
- testSearchEvent
- testTodoDatesearch
- testInviteAndRespond
I tried as much as possible not to touch any actual code, besides adding "None" checks. No logic was changed.
Types were verified using typeguard (pytest extension).
Also pre-commit hooks were run.
Could you please have a look and let me know if there is anything left to do for this to get merged ?
=> Add inline typing

.pre-commit-config.yaml, CHANGELOG.md, caldav/__init__.py, caldav/davclient.py, caldav/elements/__init__.py, caldav/elements/base.py, caldav/elements/cdav.py, caldav/elements/dav.py, caldav/elements/ical.py, caldav/lib/error.py, caldav/lib/namespace.py, caldav/lib/url.py, caldav/lib/vcal.py, caldav/objects.py, examples/basic_usage_examples.py, examples/scheduling_examples.py, tests/_test_absolute.py, tests/test_caldav.py, tests/test_caldav_unit.py
- autoformat
- update config
- remove encoding line; sort imports
- comparison to `True` should be `cond is True` or `if cond:`
- linter fixes; cleanup __init__.py
=> Code formatting / style fixes:

CHANGELOG.md, caldav/objects.py, tests/test_caldav_unit.py
something like:
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:TEST
X-WR-TIMEZONE:Asia/Shanghai
BEGIN:VTIMEZONE
TZID:Asia/Shanghai
X-LIC-LOCATION:Asia/Shanghai
BEGIN:STANDARD
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
TZNAME:CST
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```
=> fix: google may return empty ical

caldav/__init__.py
This commit throws a warning rather than a ModuleNotFoundError if the `caldav._version`-module cannot be found
=> fixing an setuptools_scm annoyance

CHANGELOG.md, tests/compatibility_issues.py, tests/test_caldav.py
=> workaround for https://github.com/python-caldav/caldav/issues/360

CHANGELOG.md, caldav/davclient.py, tests/test_caldav.py, tests/test_caldav_unit.py
see also #385
Also, the previous code had a dangerous usage of a default `{}` sent as function parameter.  I didn't change it, but at least now the dict passed is a read-only thing.
We need some test code and a changelog item before this can be merged.
=> Make it possible to modify User-Agent

caldav/__init__.py, tests/test_caldav.py
An "import *" was removed in above commit.  Yes, "import *" is bad practice - but since those things are reimported other places, we can't remove it in a minor release.  First we need some kind of deprecation notice, then we need to remove it when doing a major release.  I aim for every major release to be backward compatible with everything that wasn't marked as deprecated in the previous x.0.0 major release, so 3.0 is the earliest we can remove this.
=> Partial revert of 075841971b603bbe5774880ee1fa6abf778b84b0

.github/workflows/tests.yaml
Not sure if there is any real benefit from this update. Only if your tests are very long.
=> try use new versions github-actions and drop unsupported python3.7

caldav/davclient.py, caldav/objects.py
this PR copy resolver problem #408
=> copy resolve mut arg in funcs, methods

caldav/objects.py
no needed .keys() for iterable by key
=> remove extra .keys()

caldav/davclient.py, tests/test_caldav_unit.py
1. bytecode faster
2. the code is easier
3. speed finding elements in set O (1) (hashable elemets)
=> refactoring maps code on set comprehension

examples/get_events_example.py
just yet another example(found on stackoverflow)
=> feat: another example of using

pyproject.toml, tox.ini
Coverage fully support test coverage. Pytest cov not used.
=> Remove unused dep pytest-cov.

CHANGELOG.md, caldav/objects.py, tests/test_caldav.py
Closes #432
There are some import order changes, I'm assuming that was tox as it has nothing to do with what I've done.
=> Allow to reverse the sorting order on search function 

caldav/lib/vcal.py
This PR merges the two fix up log messages into one. The diff log can be confusing when the log is viewed outside the console. (see image from Home Assistants log view)
~~I haven't touched the log level yet.~~
See: https://github.com/python-caldav/caldav/issues/426#issuecomment-2395409450
=> Change fixup log lvl to warning and merge diff log messages into related parent log

caldav/objects.py, tests/test_caldav.py
=> Don't use `datetime.utcnow()`.

caldav/davclient.py, tests/compatibility_issues.py, tests/test_caldav.py
I will try getting the test suite work for purelymail.
First commit here seems to be a true bugfix for #435 and should go into the upcoming release, cherry-picked if this pull request is not completed in time.
=> Purelymail support (WIP)

caldav/objects.py, tests/compatibility_issues.py, tests/test_caldav.py
updates https://github.com/python-caldav/caldav/issues/439
=> Make tests ignore broken server-side expand for radicale

CHANGELOG.md, caldav/davclient.py, tests/test_caldav_unit.py
Resolves https://github.com/python-caldav/caldav/issues/391
=> CHange default User-Agent from Mozilla/5 to python-caldav/$version

CHANGELOG.md, caldav/objects.py, tests/test_caldav.py
Ref #448, if someone writes `calendar.search(..., sort_keys=("DTSTART"))` rather than `calendar.search(..., sort_keys=("DTSTART",))`, it's probably a good thing if it just works.
=> Convenience fix: allow strings in `sort_keys`

.github/workflows/tests.yaml, pyproject.toml, tox.ini
include support python3.13 with formating yaml files
=> add python3.13 and autoformat yaml files

caldav/davclient.py, caldav/requests.py, pyproject.toml, tests/conf.py, tests/test_caldav.py, tests/test_caldav_unit.py
try rebase old changes in new PR
history messages 
- #452
=> use niquests

tests/_test_absolute.py, tests/proxy.py, tests/test_caldav.py
=> replace init classes on python3

caldav/objects.py
This should be a workaround for getting calendar information out from the Lark/Feishu systems - see #459 
It's not optimized for speed, more work on this later when we get the server quirk hints in place (ref #402)
=> Load by using a multiget

caldav/objects.py, tests/test_caldav_unit.py
`CalendarObjectResource`'s `_set_icalendar_component`, if the target had more than one subcomponent, would always fail because the variable `language` was not defined. I reckon this was a copy & paste bug. Contributing a simple fix with unit test.
=> Fixing _set_icalendar_component: language not defined

caldav/objects.py
Fixes #471 
`pytest` looks the same before and after modifications
`tox -e style` has been run: no changes made
=> Servers that return a quoted URL in their path will now be parsed correctly

caldav/davclient.py, caldav/objects.py
Related to #471 and #472 
After having a deeper look at it, it seems that unquoting all properties could make other servers break.
I propose that we only apply a fix when the situation requires it only.
This will reduce error logging and hopefully won't break other servers.
This is the request and reply this PR addresses:
URL: `https://confluence.domain.com/plugins/servlet/team-calendars/caldav/principals/users/user@domain.com/`
Method: PROPFIND
RESPONSE:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DAV:multistatus xmlns:DAV="DAV:" xmlns="urn:ietf:params:xml:ns:caldav" xmlns:AI="http://apple.com/ns/ical/" xmlns:BSS="http://bedeworkcalserver.org/ns/" xmlns:CS="http://calendarserver.org/ns/" xmlns:ical="http://www.w3.org/2002/12/cal/ical#">
<DAV:response> …
```
=> Revert #472 and re-address #471

caldav/davclient.py, caldav/lib/vcal.py, caldav/objects.py, tests/compatibility_issues.py, tests/test_caldav.py
Ref #132.
Procrastinating the completion one, waiting for either https://github.com/jelmer/xandikos/issues/228 or https://github.com/Kozea/Radicale/issues/1266 to be fixed so that this can be easily tested.
=> WiP: Support for alarms

CHANGELOG.md, caldav/compatibility_hints.py, caldav/davclient.py, caldav/davobject.py, caldav/lib/debug.py, caldav/lib/error.py, docs/source/index.rst, tests/conf.py, tests/conf_private.py.EXAMPLE, tests/test_caldav.py
Move it from the `tests` directory to the `caldav` directory.
Rationale:
* Work on the server checker script.  It should not have to import things from the test directory - and now I'm also splitting it out as a separate repository/project, then it's not possible even to have it read from the test directory
* When I start working at #402 I will also need to have this data available as part of the actual library
=> Refactor compatibility issues

CHANGELOG.md, caldav/calendarobjectresource.py, tests/test_caldav.py
I fixed some testing accounts on DAViCal and ran through some test code that I made long ago - found some broken code and fixed it.  Scheduling should be supported
* fixes https://github.com/python-caldav/caldav/issues/163
* fixes https://github.com/python-caldav/caldav/issues/125
=> Scheduling support

caldav/calendarobjectresource.py
To solve the issue #505 
1. Removed `vcal.fix` as it has been implemented in _set_data
2. Return `load_by_multiget()` when GET fails.
=> Fix a bug in loading davobject

caldav/davclient.py
GMX server was sending some extra parameters in the XML.  Those parameters are actually included in example code in the RFC, so we should accept it silently.
=> fix for https://github.com/python-caldav/caldav/issues/209

CHANGELOG.md, docs/source/about.rst, docs/source/examples.rst, examples/google-django.py, examples/google-flask.py
Fixes https://github.com/python-caldav/caldav/issues/119
Piggy-backed in a fixup for pull request https://github.com/python-caldav/caldav/pull/507  - I had forgotten to add the documentation file examples.rst
=> Examples on how to connect to Google - with references from the doc

CHANGELOG.md, RELEASE-HOWTO.md, caldav/calendarobjectresource.py, caldav/collection.py, caldav/davclient.py, pyproject.toml
Resolves https://github.com/python-caldav/caldav/issues/477
=> Make vobject into an optional dependency

CHANGELOG.md, caldav/collection.py, tests/test_caldav.py
A search without filtering on comp-type on a calendar containing a mix of events, journals and tasks should return a mix of such.  (All the examples in the RFC includes the comp-type filter, so many servers does not support this).  There were a bug in the auto-detection of comp-type, so tasks would typically be wrapped as events or vice-versa.
Also ensured the CHANGELOG.md contains all changes since 2.0.0 was released.
Fixes https://github.com/python-caldav/caldav/issues/539
=> Bugfix - search could give objects of wrong classes

CHANGELOG.md, README.md, caldav/collection.py, caldav/compatibility_hints.py, caldav/davclient.py, pyproject.toml, tests/conf.py, tests/conf_private.py.EXAMPLE, tests/test_caldav.py
This is very much work in progress as for now.  Come back later :-)
=> compatibility hints refactored - work in progress

caldav/lib/vcal.py
This change makes the event fixer use the "caldav" logger used otherwise througout the project instead of global logging.
This will allow for complete muting of the warning messages when an event is automatically adjusted.
It's probably easier than forcing e.g. Apple to be standards compliant.
https://github.com/python-caldav/caldav/issues/426#issuecomment-2397075495
https://github.com/home-assistant/core/issues/111633
=> Use dedicated logger when fixing events

caldav/calendarobjectresource.py, caldav/compatibility_hints.py, caldav/lib/vcal.py, tests/test_caldav.py
Users of the library are trying to push icalendar Event objects into the caldav library, and it fails.  The CalDAV protocol demands that each "calendar object resource" is wrapped in an icalendar Calendar, but one of the objectives with this library is that users should not need to know many details about the CalDAV protocol.  Hence this should be possible.
Solves #546 
Partial fix for #541
Caveat: the fix has two code paths, one for the (yet to be published) icalendar>=7 and another for icalendar<7.  However, the test code will only run on icalendar>=7 - meaning that this fix has not been verified for icalendar 6.
=> accept icalendar event/todo objects and not only calendar
