tests/test_caldav.py
Fixed a little error in an integration test
=> Failing test fixed

caldav/elements/ical.py, caldav/lib/namespace.py
Adding Apples ical namespace to allow retrieving of the calendar color and order.
=> Added Apple ical namespace and properties

example/icloud_example.py
It was mentioned in #3, this does it.
=> Update iCloud example to use Requests

caldav/elements/cdav.py
=> [cdav] Allow [None, end) in addition to [Start, None)

caldav/objects.py
=> [objects] Unfold lines before checking for UID

caldav/elements/dav.py
(https://tools.ietf.org/html/rfc4791) chapter : 5.3.4
=> Add GetEtag class to get "etag" element

caldav/objects.py
Caldav is not working with iCloud without these changes. There are probably better solutions than mine.
=> Necessary for iCloud..

caldav/elements/cdav.py, caldav/objects.py, setup.py, tests/test_cdav.py
As discussed in #58, the function can be removed altogether.
=> Remove fix tz

tests/compatibility_issues.py
Enable tests of recurring events against Xandikos.
=> Enable tests of recurring events against Xandikos

caldav/davclient.py
Some servers, like really old SabreDAV based servers, seem to choke on
password if we pass a bytes sequence instead of a string to the
"requests" libraries HTTPDigestAuth object.
This fix against v0.8-stable retries authentication in case of authentication failure with
the same password as plain string.
Related: #166 (same fix, but for master branch)
=> Fix HTTP Auth failure with old (pre UTF-8) servers (version for v0.8 stable)

caldav/davclient.py
Fixes Issue #175, proposal to add close method
=> Add proposal from #175

caldav/davclient.py
Fixes #192 
Allow the library to work with servers supporting multiple authentication methods, for instance when the `WWW-Authenticate` header returned is:
```
Bearer realm="Foobar", Basic realm="Foobar", charset="UTF-8", Basic realm="Foobar", charset="UTF-8", Basic realm="Foobar", charset="UTF-8"
```
=> Support for multiple authentication methods server headers

tests/conf.py
Add missing import of logging.
=> Add missing import of logging

caldav/lib/url.py, caldav/objects.py, tests/compatibility_issues.py, tests/conf.py, tests/test_caldav_unit.py
automated style checks sometimes have unintended side effects ... on a checklist going from 1 to 10, I'd say it's more important that the tenth step wraps the lines in the same way as the preceeding nine points than that some style rules are followed to the letter ... but our current test code does not agree.
=> Attempt to get tests to pass again

caldav/davclient.py
Ref https://github.com/python-caldav/caldav/issues/213
=> Improved error handling

caldav/lib/debug.py, caldav/lib/error.py, caldav/objects.py, setup.py, tests/compatibility_issues.py, tests/test_caldav.py
This is work in progress - but I probably need a merge request for pipelines to be run?
=> doing some refactoring and preparing for a new search method

.github/workflows/tests.yaml, setup.cfg
This runs the tests with python 3.11
=> Python 3.11 support

tests/compatibility_issues.py, tests/test_caldav.py, tests/test_caldav_unit.py
Misc improvements and addings to the tests
=> More test code

caldav/davclient.py, caldav/requests.py
Github won't allow me to reopen #257 
So, if a username has been provided, digest then basic auth will be attempted, and if no username has been provided then bearer auth will be attempted.
=> Bearer authentication support

caldav/lib/vcal.py
Resolves https://github.com/home-assistant/core/issues/86938
=> rate-limiting of error messages when encountering broken ical

tests/compatibility_issues.py, tests/test_caldav.py
... and particularly some more compatibility-fixes for letting tests pass with DAViCal
=> Test improvements

caldav/__init__.py, changelog-1.1.md
Changelog and new version number
=> Preparing for release

caldav/__init__.py, caldav/lib/vcal.py, changelog-1.1.md, tests/compatibility_issues.py
references https://github.com/home-assistant/core/issues/86938#issuecomment-1440997287
=> Minor bugfix in error logging

caldav/davclient.py
=> Allow passing custom HTTP headers to DAVClient

changelog-1.2.md
I'm regretting a bit on my "protected branch"-policy to force all commits to the master branch to be done through pull requests.  It does cause me to think a bit more and organize myself a bit better, but it also causes lots of minor fixups to be included as separate pull requests ...
=> V1.2 - try #2

caldav/davclient.py, tests/test_caldav.py
This should raise the proper error on password problems.
(the authentication code is a constant annoyance ... IMHO this should be taken care of by the requests library)
=> Bugfix 295

examples/basic_usage_examples.py, tests/test_caldav_unit.py
unit test and documentation related to https://github.com/python-caldav/caldav/issues/285
=> add unit test and documentation for custom HTTP headers 

caldav/objects.py
Potential workaround for issue #302
=> Workaround 302

caldav/objects.py
Add the possibility to have extra props for search function.
My needs is to add `props=[dav.GetEtag()]` in the search.
=> add props parameter to search function

caldav/lib/vcal.py, caldav/objects.py, setup.py, tests/test_caldav.py
`get_relatives`-method so far.   Maybe there will be more methods.
Needed for my `plann`-project
=> Methods for handling relationships

CHANGELOG.md, caldav/objects.py, docs/source/index.rst, examples/sync_examples.py, setup.cfg
(Procrastinating merge of this, to piggy-back several bugfixes into one pull request)
* Examples file has been improved, forgot to save the sync token to the database
=> Misc minor bugfixes

CHANGELOG.md, caldav/lib/vcal.py, caldav/objects.py, tests/test_caldav.py
Resolves issue #352, and some other minor bugs.
=> Refactoring the sort algorithm, fixing some bugs

CHANGELOG.md, caldav/davclient.py, caldav/lib/error.py, caldav/objects.py
Updates #248
Not production-ready and will most likely not hit the next release.
=> debug option to write all server communication to persistent tempfiles

CHANGELOG.md, tests/compatibility_issues.py, tests/test_caldav.py
Also added posteo quirks into compatibility_issues
This solves issue #361
=> tests were a bit broken for calendars without mkcalendar.

tests/compatibility_issues.py, tests/test_caldav.py
* quite some bugfixes in latest releases of davical, most of the incompatibility notices are obsoleted.
* found an incompatibility in Posteo.
* found a bug in the test code
=> Fixing ftests and compatibility matrix

CHANGELOG.md, caldav/lib/vcal.py, tests/test_caldav.py, tests/test_vcal.py
Making some existing code more robust
=> COMPLETED should be a timestamp and not a date

CHANGELOG.md, caldav/__init__.py, caldav/objects.py, tests/test_caldav.py, tests/test_caldav_unit.py
Batching up various minor fixes into one pull-request.
=> Various bugfixes

caldav/objects.py
https://realpython.com/iterate-through-dictionary-python/
=> by default dict loops yield only key

caldav/objects.py
here list comprehension can improve performance
=> use list comprehension, more faster this usecase

caldav/davclient.py
https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil
=> change mut arg on None and added checker is None

caldav/davclient.py, caldav/elements/base.py, caldav/lib/error.py, caldav/lib/namespace.py, caldav/lib/url.py, caldav/objects.py
unreadable typing.<types>
I changed imports(use objects from typing)
=> replace typing.* in imports type objects

caldav/elements/base.py
extra code, using pythonic designs
=> copy resolving extra code with PR #405

caldav/lib/url.py
you can check some types with isinstance func
=> use isinstance with tuple classes

caldav/objects.py
use linking vars in one line  with `or`
=> filters var linking in on line

.pre-commit-config.yaml, caldav/davclient.py, caldav/elements/base.py, caldav/elements/cdav.py, caldav/elements/dav.py, caldav/elements/ical.py, caldav/lib/vcal.py, caldav/objects.py, examples/scheduling_examples.py, tests/test_caldav.py, tests/test_caldav_unit.py, tests/test_cdav.py, tests/test_vcal.py
remove incorrect args for pre-commit, using by default
result - correcting imports
=> incorrect args `["--application-directories", "src"]`, nothing doing

.github/workflows/tests.yaml
=> change version action cache to latest - 4

pyproject.toml
Extend classifiers , information python available versions
=> Clarify python 3.7-3.12

pyproject.toml
This adds a few links to PyPI so people find the docs a bit easier on the side.
=> Add more project links to PyPI

docs/source/index.rst
I was looking at how to test and github actions uses this. So, I think this is the way to go.
=> Document how to use tox for testing

caldav/objects.py
=> Skip nonexisting calendars

CHANGELOG.md, caldav/objects.py
I don't know why this fell through the cracks ... this solves #459, but I forgot merging it?
=> if we cannot load an object using GET, try using REPORT and multiget

caldav/collection.py, tests/test_caldav.py
fix for https://github.com/python-caldav/caldav/issues/237 + some refactoring
=> support easy search for journals

CHANGELOG.md, caldav/calendarobjectresource.py, caldav/compatibility_hints.py, tests/test_caldav.py
This solves #379 
Bonus: now it's also possible to make changes to a recurrence object and ask for the whole series to be changed.
=> Allow recurrence objects to be changed.
